### ISSUE TITLE
Memory Leak reported in core

### ISSUE THREAD

**Issue by assimoes** [APIDevTools/swagger-parser#121]
Hello!

I have been using swagger-parser since version 4.x.x, mostly as a dependency of `hapi-swagger`. I have never had the need to create a service that uses `swagger-parser` directly. However, today I had that need and every time I require this package, the test runner reports a memory leak in `core`.

![image](https://user-images.githubusercontent.com/6333324/60342625-eca0e180-99a9-11e9-953e-8b39aefde561.png)

If I comment the require to this package on my SUT the memory leak is no longer reported.

Also, I have tried several versions of this package including the latest. The issue is the same.

Any hints?

**Comment by JamesMessinger** [comment]
What tool are you using to detect leaks?  Are you sure this is a *memory* leak? Based on the screenshot you posted, it looks like a *global* leak, not a memory leak.

**Comment by assimoes** [comment]
Hi, you are right. It is a global leak. 
Im using labjs.

**Comment by assimoes** [comment]
Truth is we have been using this lib for quite a while without any side effects.

**Comment by JamesMessinger** [comment]
I don't think this is anything in Swagger Parser.  It may be in some dependency of Swagger Parser, or it may be in some dependency of your application.  My _hunch_ is that it's caused by [core-js](https://www.npmjs.com/package/core-js), which could be getting injected into your build if you're using a transpiler/bundler such as Babel, TypeScript, WebPack, etc.

I'm going to mark this issue as closed, but feel free to continue commenting here if you have more questions or if you discover the culprit.  I'd love to know!

**Comment by assimoes** [comment]
That is indeed the case. After checking other of our internal projects, we
are ignoring core-js global leaks on the test runner.

A sábado, 29/06/2019, 14:11, James Messinger <notifications@github.com>
escreveu:
