### ISSUE TITLE
Online validator is becoming unresponsive

### ISSUE THREAD

**Issue by ashishsanodia-harness** [APIDevTools/swagger-parser#221]
Hi ,
I was trying to online validate openapi specification downloaded from here https://harness.io/docs/api/ . But online swagger-parser is becoming unresponsive forever.

**Comment by 255kb** [comment]
I noticed this too using the `dereference` methods of the library, with some OAS files, two examples: 

- Stripe: https://api.apis.guru/v2/specs/stripe.com/2020-08-27/openapi.json
- Bungie: https://api.apis.guru/v2/specs/bungie.net/2.11.1/openapi.json

Everything was working fine with v10.0.3, but since v10.1.0 it's taking forever (like 30mn or even hours for Stripe).

**Comment by sarike** [comment]
@255kb 

If you are using yarn, add below code in your `package.json` can resolve this issue.

```json
  "resolutions": {
    "@apidevtools/json-schema-ref-parser": "9.0.7"
  },
```
