### ISSUE TITLE
Update Changelog for 3.4 Release

### ISSUE THREAD

**Issue by danielgtaylor** [APIDevTools/swagger-parser#29]
Looks like the changelog hasn't been updated for the latest release. Just letting you know! :sunglasses:

**Comment by BigstickCarpet** [comment]
Good point.  Thanks for the catch.  To be honest, the `v3.4.0` release probably should have been `v3.3.1` since there weren't any major changes or new features added.  Almost [all of the commits](https://github.com/BigstickCarpet/swagger-parser/compare/v3.3.0...v3.4.0) were changes to unit tests, not the actual library code.   The only "real" code changes were a [bug fix](https://github.com/BigstickCarpet/swagger-parser/commit/7c06a7b0310b86c1a86e57183f9939eefdb1e17b) and [updated dependencies](https://github.com/BigstickCarpet/swagger-parser/commit/aacb9ea70e391b6c062b5ee88bb584a34f0729f7)

I'm planning to release `v4.0.0` sometime this week, which _really does_ contain major changes.  So I'll be sure to update the changelog for that release.
