### ISSUE TITLE
Invalid $ref pointer

### ISSUE THREAD

**Issue by kokyhin** [APIDevTools/swagger-parser#81]
I have next API file - api.yaml

```
swagger: '2.0'
info:
  title: TEST
  version: '2.0'
paths:
  /path:
    get:
      operationId: _GET
      responses:
        '100':
          description: description
          schema:
            $ref: '#/definitions/datatype'
basePath: /
host: 'name.com'
definitions:
  datatype:
    $ref: './schemas/datatype.json#datatype'
```

when i'm calling 

```
SwaggerParser.bundle(file, (error, project) => {
      if (error) {
         return reject(error);
     }
     return resolve(project);
 });
```
Throws error "Invalid $ref pointer "datatype". Pointers must begin with "#/""

When i'm adding options 
```
SwaggerParser.bundle(file, {
  resolve: {
    external: true,
    file: true
  }
}, (error, project) => {
  if (error) {
    return reject(error);
  }
  return resolve(project);
});
```

Throws error "Unable to resolve $ref pointer "api.yaml"

**Comment by BigstickCarpet** [comment]
The issue here is with the following reference: `./schemas/datatype.json#datatype`

The hash portion of this URL is not a valid JSON Reference.  All JSON References [must begin with a slash](https://tools.ietf.org/html/draft-ietf-appsawg-json-pointer-04#section-3).  If you want the reference to point to the _entire_ `datatype.json` file, then just remove the hash portion of the URL, so it becomes `./schemas/datatype.json`.  Or, if you want the reference to point to a `datatype` property that's at the first level of `datatype.json`, then just add a slash at the beginning of the hash so it becomes `./schemas/datatype.json#/datatype`.

**Comment by aymen94** [comment]
Can we close this ticket as invalid?
Thanks @JamesMessinger
