### ISSUE TITLE
Add typescript definitions for public api

### ISSUE THREAD

**Issue by BenSayers** [APIDevTools/swagger-parser#91]
As a developer using typescript I would like this library to include typescript definitions for it's public API so I can catch integration issues earlier in the dev cycle and have a smooth experience integrating with this library in typescript. 

Today there are definitions on DefinitelyTyped but they are outdated.

**Comment by BigstickCarpet** [comment]
Agreed.  I'd gladly approve a PR adding a TypeScript definition file.  `swagger-parser` is just a wrapper around `json-schema-ref-parser` (another library of mine) and someone recently added [a TypeScript definition file](https://github.com/BigstickCarpet/json-schema-ref-parser/blob/master/lib/index.d.ts) to that project.  I suspect that it would only require minor changes to make that definition work for Swagger Parser, since the APIs of both projects are pretty much the same

**Comment by ffflorian** [comment]
The definitions can be found [in DefinitelyTyped](https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/types/swagger-parser).

**Comment by JamesMessinger** [comment]
The latest release now includes TypeScript definitions

**Comment by BenSayers** [comment]
Awesome, thanks @JamesMessinger!
