### ISSUE TITLE
internal reference problem

### ISSUE THREAD

**Issue by tiaanm** [APIDevTools/swagger-parser#99]
Hi

Let me start by stating that I might have the terminology of internal reference wrong here.

I have a swagger that I need to load, add some stuff and then dump.

Using version 3.4.1 passing {$refs: {internal: false}} as option to validate function and dumping the swagger with js-yaml it would maintain the references from parameter and response objects.

Updating to version 5.0.0 or 6.0.0 it now duplicates the definition to the parameter or response object.

Sample Swagger

swagger: '2.0'
info:
  version: 1.0.0
  title: Sample Swagger
schemes:
  - https
consumes:
  - application/json
produces:
  - application/json
basePath: /
paths:
  /path1:
    post:
      description: sample post
      parameters:
        - name: body
          in: body
          schema:
            $ref: '#/definitions/SampleBody'
      responses:
        '200':
          description: Created. The reoprt is created and the location URL is returned
          schema:
            $ref: '#/definitions/SampleResponse'
definitions:
  SampleBody:
    type: object
    properties:
      sampleRequestString1:
        type: string
      sampleRequestString2:
        type: string
      sampleRequestNumber:
        type: number
  SampleResponse:
    description: The report location URL 
    type: object
    properties:
      sampleResponseString:
        type: string

Sample code that just reads and dumps the swagger

var yaml = 'test-ref.yaml';
var yamldump = require('js-yaml');

const SwaggerParser = require('swagger-parser');
const parser = new SwaggerParser();

parser.validate(yaml, {
  $refs: {
    internal: false
  }
})
  .then((api) => {

    console.log(
      yamldump.dump(api, {
        flowLevel: -1,
        styles: {
          '!!int': 'hexadecimal',
          '!!null': 'camelcase'
        }
      })
    );

  })
  .catch((err) => {
    console.log(err.message);
  });

Out using 3.4.1

swagger: '2.0'
info:
  version: 1.0.0
  title: Sample Swagger
schemes:
  - https
consumes:
  - application/json
produces:
  - application/json
basePath: /
paths:
  /path1:
    post:
      description: sample post
      parameters:
        - name: body
          in: body
          schema:
            $ref: '#/definitions/SampleBody'
      responses:
        '200':
          description: Created. The reoprt is created and the location URL is returned
          schema:
            $ref: '#/definitions/SampleResponse'
definitions:
  SampleBody:
    type: object
    properties:
      sampleRequestString1:
        type: string
      sampleRequestString2:
        type: string
      sampleRequestNumber:
        type: number
  SampleResponse:
    description: The report location URL
    type: object
    properties:
      sampleResponseString:
        type: string

Output using version 5.0.0 or 6.0.0

swagger: '2.0'
info:
  version: 1.0.0
  title: Sample Swagger
  x-ibm-name: sample-swagger
schemes:
  - https
consumes:
  - application/json
produces:
  - application/json
basePath: /
paths:
  /path1:
    post:
      description: sample post
      parameters:
        - name: body
          in: body
          schema:
            type: object
            properties:
              sampleRequestString1:
                type: string
              sampleRequestString2:
                type: string
              sampleRequestNumber:
                type: number
      responses:
        '200':
          description: Created. The reoprt is created and the location URL is returned
          schema:
            description: The report location URL
            type: object
            properties:
              sampleResponseString:
                type: string
definitions:
  SampleBody:
    type: object
    properties:
      sampleRequestString1:
        type: string
      sampleRequestString2:
        type: string
      sampleRequestNumber:
        type: number
  SampleResponse:
    description: The report location URL
    type: object
    properties:
      sampleResponseString:
        type: string

It there another way of achieving in version 6.0.0 what I got in version 3.4.1

Thanks

**Comment by JamesMessinger** [comment]
Oh wow... jumping from v3 to v6 is a big jump.  There have been a lot of changes since then, so you might want to review [the changelog](https://github.com/APIDevTools/swagger-parser/blob/master/CHANGELOG.md) to see what changes you need to make to your code.

There are two problems that I see off-hand.  First, the `$refs.internal` option was removed in version 4.0.0.   Second, [the `validate()` method](https://apidevtools.org/swagger-parser/docs/swagger-parser.html#validateapi-options-callback) that you're currently using calls [the `dereference()` method](https://apidevtools.org/swagger-parser/docs/swagger-parser.html#dereferenceapi-options-callback) internally, which causes **all** `$ref` pointers to be replaced with the objects that they point to.  That's why you're seeing duplicate objects in your output.

If your swagger definition is all in a single file, then you can use [the `parse()` method](https://apidevtools.org/swagger-parser/docs/swagger-parser.html#parseapi-options-callback) to read the file without affecting any of the internal `$ref` pointers in it.   Or, if your swagger definition is spread out across many files, using `$ref` pointers to point from one file to another, then you should use [the `bundle()` method](https://apidevtools.org/swagger-parser/docs/swagger-parser.html#bundleapi-options-callback) to bundle all the files into a single object while keeping any internal `$ref` pointers intact.
